# Generated by Django 3.2.6 on 2021-11-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicShop', '0002_auto_20211125_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='MusicShop.CartProduct', verbose_name='Продукты для корзины'),
        ),
    ]
