# Generated by Django 3.2.6 on 2021-11-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicShop', '0003_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Общая цена'),
        ),
    ]
