# Generated by Django 3.2.6 on 2021-11-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicShop', '0004_alter_cart_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(),
        ),
    ]
