# Generated by Django 3.2.6 on 2021-11-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicShop', '0005_alter_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='out_of_stock',
            field=models.IntegerField(default=False, verbose_name='Нет в наличии'),
        ),
    ]
